name: Deploy Action
run-name: ${{ github.actor }} is testing out ssh GitHub Actions 🚀
on:
  push:
    branches:
      - main
jobs:
  build-image-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository code
        uses: actions/checkout@v4
      - name: Set up JDK 21
        uses: actions/setup-java@v3
        with:
          java-version: '21'
          distribution: 'microsoft'
          cache: 'sbt'
      - name: Log in to Docker Hub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
      - name: Build and push image
        run: |
          sudo echo '${{ secrets.YDB_CERTIFICATE }}' > cert_file.sa
          export CERT_FILE=cert_file.sa
          export CONN_STRING=${{ secrets.YDB_CONN_STRING }}
          sbt dockerBuildAndPush
      - name: Download image and restart container
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.SSH_HOST }}
          key: ${{ secrets.SSH_SECRET_KEY }}
          passphrase: ${{ secrets.SSH_PASSPHRASE }}
          username: ${{ secrets.SSH_USERNAME }}
          script: sudo ./back/full_reboot.sh
